services:
  web:
    image: php:8.1-apache-bullseye
    container_name: lamp_web
    ports:
      - "80:80"
    networks:
      - lamp_network
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:9
    container_name: lamp_db
    networks:
      - lamp_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
  # PHP my admin is Only for Lab purposes
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lamp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lamp_network


volumes:
  db_data:

networks:
  lamp_network:
