version: '3.8'

services:
  web:
    image: php:8.1-apache-bullseye
    container_name: lamp_web
    ports:
      - "8080:80"
    networks:
      - lamp_network
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:latest
    container_name: lamp_db
    networks:
      - lamp_network
    environment:
      MYSQL_ROOT_PASSWORD: value
      MYSQL_DATABASE: lamp_db
      MYSQL_USER: lamp_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:

networks:
  lamp_network:


  